baseURL = "http://mikegsrv.ru/"
bind = "0.0.0.0"
languageCode = "en-us"
title = "Mikhail Gusarov"
theme = "vncnt-hugo"
version = "0.0.1"

[params]
author = "Mikhail Gusarov"
description = ""
bio = "Developer @ Home (Unemployed)"
avatar = "avatar.png"
favicon = "favicon.ico"

        [params.contact]
        github = "mikegsrv"
        telegram = "mikegsrv"
        linkedin = "mikegsrv"

        [params.contact.email]
        name = "email"
        icon = "envelope"
        link = "mailto:mikhail@gusarov.dev"
