baseURL = "http://gusarov.dev/"
bind = "0.0.0.0"
languageCode = "en-us"
title = "Mikhail Gusarov"
theme = "vncnt-hugo"
version = "1.0.0"

[module]
[[module.mounts]]
	includeFiles = '*.pdf'
	source = 'cv'
	target = 'static'
[[module.mounts]]
	source = 'static'
	target = 'static'

[params]
author = "Mikhail Gusarov"
description = ""
bio = "Frontend Engineer @ Avito"
avatar = "avatar.png"
favicon = "favicon.ico"

        [params.contact]
        github = "https://github.com/mikegsrv"
        telegram = "https://t.me/mikegsrv"
        linkedin = "https://linkedin.com/in/mikegsrv"

        [params.contact.email]
        name = "email"
        icon = "envelope"
        link = "mailto:mikhail@gusarov.dev?subject=Contact%20Mikhail%20Gusarov%20"
